Project3: TestDriver.o getInt.o Universe.o Character.o Barbarian.o Menu.o Vampire.o BlueMen.o Medusa.o HarryPotter.o
	g++ TestDriver.o getInt.o Universe.o Character.o Barbarian.o Menu.o Vampire.o BlueMen.o Medusa.o HarryPotter.o -std=c++0x -o Project3

TestDriver.o: TestDriver.cpp
	g++ -std=c++0x -c TestDriver.cpp

getInt.o: getInt.cpp getInt.hpp
	g++ -std=c++0x -c getInt.cpp

Universe.o: Universe.cpp Universe.hpp
	g++ -std=c++0x -c Universe.cpp

Character.o: Character.cpp Character.hpp
	g++ -std=c++0x -c  Character.cpp

Barbarian.o: Barbarian.cpp Barbarian.hpp
	g++ -std=c++0x -c Barbarian.cpp

Menu.o: Menu.cpp Menu.hpp
	g++ -std=c++0x -c Menu.cpp

Vampire.o: Vampire.cpp Vampire.hpp
	g++ -std=c++0x -c Vampire.cpp

BlueMen.o: BlueMen.cpp BlueMen.hpp
	g++ -std=c++0x -c BlueMen.cpp

Medusa.o: Medusa.cpp Medusa.hpp
	g++ -std=c++0x -c Medusa.cpp

HarryPotter.o: HarryPotter.cpp HarryPotter.hpp
	g++ -std=c++0x -c HarryPotter.cpp

clean:
	rm *.o Project3

